version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '/'
    reviewers:
      - 2hoch1
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: 'chore'
      prefix-scope: deps
      include: 'scope'
    allow:
      - dependency-type: all
    rebase-strategy: auto
